### ISSUE TITLE
Publish One Device Operator in Operator Hub

### ISSUE THREAD

**Issue by msivosuo** [intel/intel-device-plugins-for-kubernetes#385] opened 2020-06-03 11:17 UTC
Publish One Device Operator in Operator Hub

**Comment by rojkov** [comment] 2020-09-15 09:41
I have to pause this task due to https://github.com/operator-framework/operator-lifecycle-manager/issues/1315#issuecomment-692597350

**Comment by rojkov** [comment] 2020-11-25 12:43
The progress can be tracked at https://github.com/operator-framework/community-operators/pull/2750 now.

**Comment by msivosuo** [comment] 2020-12-15 12:59
@rojkov - could we ping operator-framework people on this to get some traction?

**Comment by rojkov** [comment] 2020-12-15 14:02
I've managed to find to [this instruction](https://operator-framework.github.io/community-operators/#test-your-operator-before-submitting-a-pr) on how to reproduce the CI tests locally. But I'm busy with a QAT engine issue ATM. Will try it later.

**Comment by pohly** [comment] 2020-12-15 17:23
@avalluri has added CI testing of the PMEM-CSI operator. He can provide further pointers and help in case that you need it.

**Comment by rojkov** [comment] 2021-01-05 15:27
Closing as https://github.com/operator-framework/community-operators/pull/2750 got merged.

**Closed by rojkov** 2021-01-05 15:27 UTC
Labels: operator
